# Generated by Django 3.0.2 on 2020-01-27 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='change_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date of change'),
            preserve_default=False,
        ),
    ]
