# Generated by Django 3.0.2 on 2020-01-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productlog_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='change_date',
            field=models.DateField(verbose_name='Date of change'),
        ),
    ]
