# Generated by Django 3.0.2 on 2020-01-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200127_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductLog',
            new_name='Log',
        ),
    ]
