# Generated by Django 3.0.2 on 2020-01-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200128_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='change_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='input_quantity',
        ),
        migrations.RemoveField(
            model_name='log',
            name='output_quantity',
        ),
        migrations.AddField(
            model_name='log',
            name='income',
            field=models.IntegerField(default=0, verbose_name='Income'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='outcome',
            field=models.IntegerField(default=0, verbose_name='Outcome'),
            preserve_default=False,
        ),
    ]
